### ISSUE TITLE
per-distro branches

### ISSUE THREAD

**Issue by mintar** [uos/rviz_fps_plugin#2]
I would suggest creating one branch per distro (`hydro`, `indigo`) instead of the current system (`master` = catkin, `rosbuild`). I know it sucks that you always have to "tag along" all branches even if they are aliases, but it saves a lot of work to properly split the branches *before* they start to deviate.

I also suggest deleting the `master` branch and setting the default branch to one of the new branches (`indigo`, for example).

@hdeeken @jspricke What do you think?

**Comment by hdeeken** [comment]
jippjipp, i agree, i'll do that later this afternoon

**Comment by hdeeken** [comment]
so i created and indigo branch and removed the rosbuild branch, but added a tag to identfiy the point where we migrated to catkin. however i'm not able to delete the origin/master since it is the github default. either i'm tired and blind to find the button to change that default branch or i'm missing some rights here. @mintar can you help out here?

i did not create a hydro branch, since i can't recall for sure which is the stable commit for hydro.
i believe that the indigo branch should be hydro compatible as well, but let's better try that first.

**Comment by jspricke** [comment]
Done, I don't think we need hydro branches or older stuff. Who is using that anyway? ;).

**Comment by mintar** [comment]
Well, I think we _do_ need hydro, and we should release this to hydro as well. I've pushed the new branch. Compilation currently fails, just as on indigo (see #4), but I've tested a0a7a15c on hydro and it worked.
